services:
  
  tests:
    build:
      context: ..
      dockerfile: BTCPayServer.Plugins.IntegrationTests/Dockerfile
    environment:
      TESTS_POSTGRES: User ID=postgres;Include Error Detail=true;Host=postgres;Port=5432;Database=btcpayserver
      TESTS_HOSTNAME: tests
      TESTS_INCONTAINER: "true"
      BTCPAY_XMR_DAEMON_URI: http://monerod:18081
      BTCPAY_XMR_WALLET_DAEMON_URI: http://xmr_wallet:18082
      BTCPAY_XMR_WALLET_DAEMON_WALLETDIR: /wallet
    depends_on:
      - postgres
      - xmr_wallet
    extra_hosts:
      - "tests:127.0.0.1"
    volumes:
      - ../coverage:/coverage
      - xmr_wallet:/wallet

  # The dev container is not used, it is just handy to run `docker-compose up dev` to start all services
  dev:
    image: alpine:3.21
    container_name: dev
    command: [ "/bin/sh", "-c", "trap : TERM INT; while :; do echo Ready to code and debug like a rockstar!!!; sleep 2073600; done & wait" ]
    depends_on:
      - postgres
      - xmr_wallet

  monerod:
    image: btcpayserver/monero:0.18.4.3
    restart: unless-stopped
    container_name: monerod
    command: monerod --fixed-difficulty 1 --log-level=2 --rpc-bind-ip=0.0.0.0 --confirm-external-bind --rpc-bind-port=18081 --block-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/block?cryptoCode=xmr&hash=%s" --regtest --no-igd --hide-my-port --offline --non-interactive
    volumes:
      - xmr_data:/data
    ports:
      - "18081:18081"

  xmr_wallet:
    image: btcpayserver/monero:0.18.4.3
    restart: unless-stopped
    container_name: xmr_wallet
    command: monero-wallet-rpc --log-level 2 --allow-mismatched-daemon-version --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon --daemon-address=monerod:18081 --wallet-dir=/wallet --tx-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s"
    ports:
      - "18082:18082"
    volumes:
      - xmr_wallet:/wallet
    depends_on:
      - monerod

  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "39372:5432"
    expose:
      - "5432"

volumes:
  xmr_data:
  xmr_wallet: